#!/usr/bin/env python2
from __future__ import absolute_import, division, print_function, unicode_literals

import rospy
import std_srvs.srv

def open_called(request):
    rospy.sleep(3.0)
    response = std_srvs.srv.TriggerResponse()
    response.success = True
    return response

def close_called(request):
    rospy.sleep(3.0)
    response = std_srvs.srv.TriggerResponse()
    response.success = True
    return response

def main():
    rospy.init_node('fake_gripper_node')

    open_srv = rospy.Service('open', std_srvs.srv.Trigger, open_called)
    close_srv = rospy.Service('close', std_srvs.srv.Trigger, close_called)

    rospy.spin()

if __name__ == '__main__':
    main()
